# Generated by Django 6.0.6 on 2026-06-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleconfig',
            name='mitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.mitretechnique'),
        ),
        migrations.AddField(
            model_name='ruleconfig',
            name='severity',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
