# Generated by Django 6.0.6 on 2026-08-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='evidence',
        ),
        migrations.AddField(
            model_name='investigation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='ASSIGNED', max_length=20),
        ),
    ]
