# Generated by Django 6.0.6 on 2026-08-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_remove_investigation_evidence_investigation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='investigations/evidence/'),
        ),
    ]
