# Generated by Django 6.0.6 on 2026-08-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_alter_investigation_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='file',
        ),
    ]
