# Generated by Django 6.0.6 on 2026-08-12 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ALERT_ASSIGNED', 'Alert Assigned'), ('INVESTIGATION_UPDATED', 'Investigation Updated'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('INVESTIGATION_COMPLETED', 'Investigation Completed'), ('ALERT_CLOSED', 'Alert Closed')], max_length=50)),
                ('description', models.TextField()),
                ('alert_id', models.IntegerField(blank=True, null=True)),
                ('investigation_id', models.IntegerField(blank=True, null=True)),
                ('evidence_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
