# Generated by Django 6.0.6 on 2026-08-12 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='evidence_id',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ALERT_ASSIGNED', 'Alert Assigned'), ('INVESTIGATION_UPDATED', 'Investigation Updated'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('INVESTIGATION_COMPLETED', 'Investigation Completed'), ('ALERT_CLOSED', 'Alert Closed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
