# Generated by Django 6.0.6 on 2026-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='evidence_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
