# Generated by Django 6.0.6 on 2026-06-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('detection', '0002_ruleconfig_mitre_ruleconfig_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='mitre_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.mitretechnique'),
        ),
    ]
