# Generated by Django 6.0.6 on 2026-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_mitre_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('FALSE_POSITIVE', 'False Positive'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
