# Generated by Django 6.0.6 on 2026-08-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_assigned_alert_status_delete_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('FALSE_POSITIVE', 'False Positive'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
