# Generated by Django 6.0.6 on 2026-06-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('last_processed_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='LogState',
        ),
    ]
