# Generated by Django 6.0.6 on 2026-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_detectionstate_delete_logstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='description',
        ),
        migrations.RemoveField(
            model_name='log',
            name='username',
        ),
        migrations.AddField(
            model_name='log',
            name='computer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='time_generated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
