# Generated by Django 6.0.6 on 2026-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_log_description_remove_log_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='computer',
        ),
        migrations.AddField(
            model_name='log',
            name='Keyword',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
