# Generated by Django 6.0.6 on 2026-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_log_computer_log_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='Computer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
