# Generated by Django 6.0.6 on 2026-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_log_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='Computer',
            new_name='computer',
        ),
        migrations.RemoveField(
            model_name='log',
            name='Keyword',
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='tactic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='technique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
