# Generated by Django 6.0.6 on 2026-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_incident_alter_alert_options_alter_log_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='mitre_id',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='tactic',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='technique',
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_technique',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(max_length=20),
        ),
    ]
