# Generated by Django 6.0.6 on 2026-06-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_alert_options_remove_alert_acknowledged_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title',
        ),
        migrations.AddField(
            model_name='incident',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='logs.alert'),
        ),
        migrations.AddField(
            model_name='incident',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
    ]
