# Brute Force Detection
BRUTEFORCE_WINDOW_MINUTES = 5
BRUTEFORCE_THRESHOLD = 5

# Brute Force Success
BRUTEFORCE_SUCCESS_WINDOW_MINUTES = 10
BRUTEFORCE_SUCCESS_THRESHOLD = 3

# Off Hours Login
OFF_HOURS_START = 20
OFF_HOURS_END = 6